# Generated by Django 2.2.1 on 2019-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20191201_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
